apiVersion: v1
kind: Service
metadata:
  name: author-service
  namespace: blogsphere-dev
  labels:
    app: author-service
    app.kubernetes.io/name: author-service
spec:
  type: ClusterIP
  selector:
    app: author-service
  ports:
    - name: http
      port: 5001
      targetPort: 5001

