apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blogsphere-dev
  labels:
    app: blog-service
    app.kubernetes.io/name: blog-service
spec:
  type: ClusterIP
  selector:
    app: blog-service
  ports:
    - name: http
      port: 5002
      targetPort: 5002

