apiVersion: v1
kind: ConfigMap
metadata:
  name: blogsphere-config
  namespace: blogsphere-dev
data:
  NODE_ENV: "production"
  USER_PORT: "5000"
  AUTHOR_PORT: "5001"
  BLOG_PORT: "5002"
  USER_SERVICE: "http://user-service.blogsphere-dev.svc.cluster.local:5000"

